# Generated by Django 5.2.12 on 2026-06-21 02:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import marketplace.models
import marketplace.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='invitation_message',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_details',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='certification',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=marketplace.models.private_upload_path, validators=[marketplace.validators.validate_private_document]),
        ),
        migrations.AddField(
            model_name='certification',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='certification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='certification',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='techniciandocument',
            name='content_type',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='techniciandocument',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('applied', 'Applied'), ('invited', 'Invited'), ('reviewed', 'Reviewed'), ('interview', 'Interview'), ('offered', 'Offer Sent'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationmessage',
            name='body',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='description',
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='techniciandocument',
            name='file',
            field=models.FileField(upload_to=marketplace.models.private_upload_path, validators=[marketplace.validators.validate_private_document]),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='workhistory',
            name='description',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(max_length=600)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CredentialAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(default='all', max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_requests', to='marketplace.employerprofile')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_requests', to='marketplace.technicianprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('employer', 'technician', 'credential_type'), name='unique_credential_access_request')],
            },
        ),
        migrations.CreateModel(
            name='EmployerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professionalism', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('workplace', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.employerprofile')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_reviews', to='marketplace.technicianprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('technician', 'employer'), name='unique_technician_employer_review')],
            },
        ),
        migrations.CreateModel(
            name='TechnicianReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reliability', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_reviews', to='marketplace.employerprofile')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.technicianprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employer', 'technician'), name='unique_employer_technician_review')],
            },
        ),
    ]
