# Generated by Django 5.2.12 on 2026-06-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_application_interview_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='content_type',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='certification',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
