# Generated by Django 5.2.12 on 2026-06-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_certification_content_type_certification_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='email_job_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
