# Generated by Django 5.2.12 on 2026-06-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_technicianprofile_email_job_alerts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='employer_notes',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
