# Generated by Django 5.2.12 on 2026-06-21 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_application_employer_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('message', 'Messages'), ('application', 'Application activity'), ('offer', 'Invitations and offers'), ('credential', 'Credential requests'), ('job_match', 'Matching jobs')], default='application', max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_messages', models.BooleanField(default=True)),
                ('email_messages', models.BooleanField(default=True)),
                ('in_app_applications', models.BooleanField(default=True)),
                ('email_applications', models.BooleanField(default=True)),
                ('in_app_offers', models.BooleanField(default=True)),
                ('email_offers', models.BooleanField(default=True)),
                ('in_app_credentials', models.BooleanField(default=True)),
                ('email_credentials', models.BooleanField(default=True)),
                ('in_app_job_matches', models.BooleanField(default=True)),
                ('email_job_matches', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
