# Generated by Django 5.2.12 on 2026-06-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('technician', 'Technician'), ('employer', 'Employer'), ('admin', 'Administrator')], default='technician', max_length=20),
        ),
    ]
