# Generated by Django 5.2.12 on 2026-06-20 22:46

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.WrenchLinkUserManager()),
            ],
        ),
    ]
